Repository WildCodeSchool/orleans-0218-kitchenkustoms, pull requests merged in 2018-04, with the labels that each got.

#14 Sprint1 US2
  app/routing.php
  public/assets/css/styles.css
  public/assets/fonts/Albertsthal Typewriter.ttf
  public/assets/fonts/linowrite.ttf
  public/assets/images/favicon.png
  public/assets/images/logo_kitchen_kustoms.png
  public/assets/images/logo_kitchen_kustoms_nav.png
  public/assets/images/logo_kitchen_kustoms_nav_mobile.png
  src/Controller/AppController.php
  src/Controller/HomeController.php
  src/View/Home/catering.html.twig
  src/View/Home/header.html.twig
  src/View/Home/index.html.twig
  src/View/Home/kustom.html.twig
  src/View/Home/shop.html.twig
  src/View/Home/workshop.html.twig
  src/View/layout.html.twig
Labels: Correction done

#18 S1 us4 footer
  public/assets/css/styles.css
  src/View/Home/footer.html.twig
  src/View/layout.html.twig
Labels: Reviewed by Po

#19 S1 us5 navbar social
  public/assets/css/styles.css
  src/View/Home/header.html.twig
  src/View/layout.html.twig
Labels: Reviewed by Po

#20 Dev
  public/assets/css/styles.css
  src/View/Home/footer.html.twig
  src/View/Home/header.html.twig
  src/View/layout.html.twig
Labels: Reviewed by Po

#24 S1_us9_01_footer_socials
  public/assets/css/styles.css
  src/View/Home/footer.html.twig
Labels: Reviewed by Po

#21 S1 us6 google map
  app/config.php
  public/assets/css/styles.css
  public/assets/js/googleMap.js
  src/Controller/HomeController.php
  src/View/Home/footer.html.twig
Labels: Correction done, Reviewed by Po

#23 S1 us15 zone txt navbar
  public/assets/css/styles.css
  src/View/Home/header.html.twig
  src/View/layout.html.twig
Labels: Correction done, Reviewed by Po

#22 S1 us8 facebook
  public/assets/css/styles.css
  public/assets/js/facebook.js
  src/View/Home/footer.html.twig
  src/View/layout.html.twig
Labels: Correction done, Reviewed by Po

#32 fix du footer de dev après merge sur dev
  public/assets/css/styles.css
  src/View/Home/footer.html.twig
  src/View/layout.html.twig
Labels: Reviewed by Po

#34 Merge dev into master
  app/config.php
  public/assets/css/styles.css
  public/assets/js/facebook.js
  public/assets/js/googleMap.js
  src/Controller/HomeController.php
  src/View/Home/footer.html.twig
  src/View/Home/header.html.twig
  src/View/layout.html.twig
Labels: Reviewed by Po

#33 création des fichiers de base pour l'interface administrateur
  app/routing.php
  public/admin/index.php
  public/assets/css/styles-admin.css
  src/Controller/Admin/AdminController.php
  src/View/Admin/header.html.twig
  src/View/Admin/index.html.twig
  src/View/layout-admin.html.twig
Labels: Reviewed by Po

#35 Dev vers master
  app/routing.php
  public/admin/index.php
  public/assets/css/styles-admin.css
  src/Controller/Admin/AdminController.php
  src/View/Admin/header.html.twig
  src/View/Admin/index.html.twig
  src/View/layout-admin.html.twig
Labels: Reviewed by Po

#38 S3 us16 admin velo list
  app/config.php
  app/routing.php
  public/admin/assets/css/styles.css
  public/assets/images/bikes/3_after.jpg
  public/assets/images/bikes/3_before.jpg
  src/Controller/AdminController.php
  src/Controller/BikeController.php
  src/Controller/HomeController.php
  src/Model/AbstractManager.php
  src/Model/Bike.php
  src/Model/BikeManager.php
  src/View/Admin/bike.html.twig
  src/View/Admin/header.html.twig
  src/View/layout-admin.html.twig
Labels: Reviewed by Po

#37 Us11 01 gallerie photos
  public/assets/css/styles.css
  public/assets/images/galleryhome/Thumb/thumb1.jpg
  public/assets/images/galleryhome/Thumb/thumb2.jpg
  public/assets/images/galleryhome/Thumb/thumb3.jpg
  public/assets/images/galleryhome/Thumb/thumb4.jpg
  public/assets/images/galleryhome/Thumb/thumb5.jpg
  public/assets/images/galleryhome/Thumb/thumb6.jpg
  public/assets/images/galleryhome/home1.jpg
  public/assets/images/galleryhome/home2.jpg
  public/assets/images/galleryhome/home3.jpg
  public/assets/images/galleryhome/home4.jpg
  public/assets/images/galleryhome/home5.jpg
  public/assets/images/galleryhome/home6.jpg
  src/View/Home/index.html.twig
Labels: Reviewed by Po

#39 S3 us13 01 accueil activites
  public/assets/css/styles.css
  public/assets/images/activities-home/atelier.jpg
  public/assets/images/activities-home/boutique.jpg
  public/assets/images/activities-home/cafe.jpg
  public/assets/images/activities-home/kustoms.jpg
  src/Controller/HomeController.php
  src/View/Home/index.html.twig
Labels: Conflicts, Correction done, Reviewed by Po

#42 Dev vers master
  app/config.php
  app/routing.php
  public/admin/assets/css/styles.css
  public/assets/css/styles.css
  public/assets/images/activities-home/atelier.jpg
  public/assets/images/activities-home/boutique.jpg
  public/assets/images/activities-home/cafe.jpg
  public/assets/images/activities-home/kustoms.jpg
  public/assets/images/bikes/3_after.jpg
  public/assets/images/bikes/3_before.jpg
  public/assets/images/galleryhome/Thumb/thumb1.jpg
  public/assets/images/galleryhome/Thumb/thumb2.jpg
  public/assets/images/galleryhome/Thumb/thumb3.jpg
  public/assets/images/galleryhome/Thumb/thumb4.jpg
  public/assets/images/galleryhome/Thumb/thumb5.jpg
  public/assets/images/galleryhome/Thumb/thumb6.jpg
  public/assets/images/galleryhome/home1.jpg
  public/assets/images/galleryhome/home2.jpg
  public/assets/images/galleryhome/home3.jpg
  public/assets/images/galleryhome/home4.jpg
  public/assets/images/galleryhome/home5.jpg
  public/assets/images/galleryhome/home6.jpg
  src/Controller/AdminController.php
  src/Controller/BikeController.php
  src/Controller/HomeController.php
  src/Model/AbstractManager.php
  src/Model/Bike.php
  src/Model/BikeManager.php
  src/View/Admin/bike.html.twig
  src/View/Admin/header.html.twig
  src/View/Home/index.html.twig
  src/View/layout-admin.html.twig
Labels: Reviewed by Po

#43 Ajout du texte de presentation
  public/assets/css/styles.css
  src/View/Home/index.html.twig
Labels: Reviewed by Po

#45 Dev vers master
  public/assets/css/styles.css
  src/View/Home/index.html.twig
Labels: Reviewed by Po

#44 Us12 01 lightbox galerie
  public/assets/js/lightboxgallery.js
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed by Po

#48 Fix footer harmonie et réseaux sociaux
  public/assets/css/styles.css
  src/View/Home/footer.html.twig
  src/View/Home/header.html.twig
Labels: Reviewed by Po

#49 Fix homepage with sections, logo and bigger images
  public/assets/css/styles.css
  public/assets/images/galleryhome/Thumb/thumb1.jpg
  public/assets/images/galleryhome/Thumb/thumb2.jpg
  public/assets/images/galleryhome/Thumb/thumb3.jpg
  public/assets/images/galleryhome/Thumb/thumb4.jpg
  public/assets/images/galleryhome/Thumb/thumb5.jpg
  public/assets/images/galleryhome/Thumb/thumb6.jpg
  public/assets/images/logo_fork_wrench.png
  src/View/Home/index.html.twig
Labels: Correction done, Reviewed by Po

#40 S3 US10 02 twig et css pour les images des liens de la navbar
  public/assets/css/styles.css
  public/assets/images/black_bg.png
  public/assets/images/black_side.png
  public/assets/images/logo_kitchen_kustoms_nav.png
  public/assets/images/white_bg.png
  public/assets/images/white_side.png
  src/View/Home/header.html.twig
Labels: Reviewed by Po

#51 Dev vers master
  public/assets/css/styles.css
  public/assets/images/black_bg.png
  public/assets/images/black_side.png
  public/assets/images/galleryhome/Thumb/thumb1.jpg
  public/assets/images/galleryhome/Thumb/thumb2.jpg
  public/assets/images/galleryhome/Thumb/thumb3.jpg
  public/assets/images/galleryhome/Thumb/thumb4.jpg
  public/assets/images/galleryhome/Thumb/thumb5.jpg
  public/assets/images/galleryhome/Thumb/thumb6.jpg
  public/assets/images/logo_fork_wrench.png
  public/assets/images/logo_kitchen_kustoms_nav.png
  public/assets/images/white_bg.png
  public/assets/images/white_side.png
  public/assets/js/lightboxgallery.js
  src/View/Home/footer.html.twig
  src/View/Home/header.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed by Po

#54 S4 us20 navbar background
  public/assets/css/styles.css
  public/assets/images/background_remaster3.png
  public/assets/images/background_remaster3_XS.png
  src/View/Home/header.html.twig
Labels: Reviewed by Po

#55 Dev vers master barre de nav avec image
  public/assets/css/styles.css
  public/assets/images/background_remaster3.png
  public/assets/images/background_remaster3_XS.png
  src/View/Home/header.html.twig
Labels: Reviewed by Po

#60 S4 us22 atelier pdf
  public/assets/css/styles.css
  public/assets/pdf/tarifs-atelier.pdf
  src/View/Home/workshop.html.twig
Labels: Reviewed by Po

#61 Dev vers master
  public/assets/css/styles.css
  public/assets/js/navbar.js
  public/assets/pdf/tarifs-atelier.pdf
  src/View/Home/header.html.twig
  src/View/Home/workshop.html.twig
  src/View/layout.html.twig
Labels: Reviewed by Po

#62 S4_US28_accueil sur la page et télécharger la carte complète.
  public/assets/css/styles.css
  public/assets/images/cafe_cantine/boissons.jpg
  public/assets/images/cafe_cantine/salle_repas.jpg
  public/assets/images/pdf/tarifs-cafe-web.pdf
  public/assets/images/wrench_and_fork_BLACK_16.svg
  src/View/Home/catering.html.twig
Labels: Reviewed by Po

#74 S4 us23 atelier carte light
  app/routing.php
  src/Controller/HomeController.php
  src/Controller/WorkshopController.php
  src/Model/AbstractManager.php
  src/Model/Workshop/CategoryWorkshop.php
  src/Model/Workshop/CategoryWorkshopManager.php
  src/Model/Workshop/ItemWorkshop.php
  src/Model/Workshop/ItemWorkshopManager.php
  src/View/Home/workshop.html.twig
Labels: Reviewed by Po

#75 S4 us35 velo admin create
  app/routing.php
  public/index.php
  src/Controller/BikeController.php
  src/Model/BikeManager.php
  src/View/Admin/addBike.html.twig
Labels: Reviewed by Po

#76 Dev vers master
  app/routing.php
  public/assets/css/styles.css
  public/assets/images/cafe_cantine/boissons.jpg
  public/assets/images/cafe_cantine/salle_repas.jpg
  public/assets/images/pdf/tarifs-cafe-web.pdf
  public/assets/images/wrench_and_fork_BLACK_16.svg
  public/index.php
  src/Controller/BikeController.php
  src/Controller/HomeController.php
  src/Controller/WorkshopController.php
  src/Model/AbstractManager.php
  src/Model/BikeManager.php
  src/Model/Workshop/CategoryWorkshop.php
  src/Model/Workshop/CategoryWorkshopManager.php
  src/Model/Workshop/ItemWorkshop.php
  src/Model/Workshop/ItemWorkshopManager.php
  src/View/Admin/addBike.html.twig
  src/View/Home/catering.html.twig
  src/View/Home/workshop.html.twig
Labels: Reviewed by Po

#87 S4 us29 read café cantine
  app/routing.php
  public/assets/css/styles.css
  src/Controller/CateringController.php
  src/Model/ItemCatering.php
  src/Model/ItemCateringManager.php
  src/View/Home/catering.html.twig
  src/View/Home/workshop.html.twig
Labels: Correction done, Reviewed by Po

#89 Dev vers master
  app/routing.php
  public/assets/css/styles.css
  src/Controller/CateringController.php
  src/Controller/WorkshopController.php
  src/Model/ItemCatering.php
  src/Model/ItemCateringManager.php
  src/Model/Workshop/CategoryWorkshopManager.php
  src/Model/Workshop/ItemWorkshopManager.php
  src/View/Admin/header.html.twig
  src/View/Admin/workshop.html.twig
  src/View/Home/catering.html.twig
  src/View/Home/workshop.html.twig
Labels: Reviewed by Po

#91 Us38 01 kustoms
  app/routing.php
  public/assets/css/styles.css
  src/Controller/BikeController.php
  src/Model/BikeManager.php
  src/View/Home/kustom.html.twig
Labels: Correction done, Reviewed by Po

#90 S4 us34 boutique liste
  app/routing.php
  public/assets/css/style_shop.css
  public/assets/fonts/Impact Label.ttf
  public/assets/images/bikes/default.png
  public/assets/images/shop/1stars.png
  public/assets/images/shop/2stars.png
  public/assets/images/shop/3stars.png
  public/assets/images/shop/4stars.png
  public/assets/images/shop/5stars.png
  public/assets/images/shop/card1.png
  public/assets/images/shop/card2.png
  public/assets/images/shop/card3.png
  public/assets/images/shop/card4.png
  public/assets/images/shop/card5.png
  public/assets/images/shop/card6.png
  public/assets/images/shop/card7.png
  public/assets/images/shop/card8.png
  src/Controller/BikeController.php
  src/Model/BikeManager.php
  src/View/Home/shop.html.twig
Labels: Correction done, Reviewed by Po

#99 Fix read cafe cantine
  src/View/Home/catering.html.twig
Labels: Reviewed by Po

#101 Fix kustom ortho
  .gitignore
  public/assets/images/bikes/1_after.png
  public/assets/images/bikes/1_before.png
  public/assets/images/bikes/3_after.jpg
  public/assets/images/bikes/3_before.jpg
  src/View/Home/kustom.html.twig
Labels: Reviewed by Po

#103 Dev vers master (les fixs)
  .gitignore
  public/assets/images/bikes/1_after.png
  public/assets/images/bikes/1_before.png
  public/assets/images/bikes/3_after.jpg
  public/assets/images/bikes/3_before.jpg
  src/Model/BikeManager.php
  src/View/Home/catering.html.twig
  src/View/Home/kustom.html.twig
Labels: Reviewed by Po

#124 Ajout des bandes et d'une image de fond.
  public/assets/css/styles.css
  public/assets/images/bg_footer.jpg
  src/View/Home/footer.html.twig
Labels: Reviewed by Po

#125 S5 us37 admin velos delete
  app/routing.php
  public/admin/assets/js/delete.js
  public/admin/index.php
  src/Controller/BikeController.php
  src/Model/AbstractManager.php
  src/View/Admin/bike.html.twig
  src/View/Admin/updateBike.html.twig
Labels: Reviewed by Po

#126 Dev To Master
  app/routing.php
  public/admin/assets/js/delete.js
  public/admin/index.php
  public/assets/css/styles.css
  public/assets/images/bg_footer.jpg
  src/Controller/BikeController.php
  src/Model/AbstractManager.php
  src/View/Admin/bike.html.twig
  src/View/Admin/updateBike.html.twig
  src/View/Home/footer.html.twig
Labels: Reviewed by Po

#127 S5_US39_Boutique_Label_Vendu
  public/assets/css/style_shop.css
  public/assets/images/shop/SOLD.png
  src/View/Home/shop.html.twig
Labels: Reviewed by Po

#128 S5 us25 atelier create
  app/routing.php
  public/admin/assets/css/styles.css
  src/Controller/WorkshopCategoryController.php
  src/Controller/WorkshopController.php
  src/Model/AbstractManager.php
  src/Model/Workshop/CategoryWorkshopManager.php
  src/Validation/CategoryWorkshopValidator.php
  src/Validation/ItemWorkshopValidator.php
  src/View/Admin/header.html.twig
  src/View/Admin/workshop.html.twig
  src/View/Admin/workshopCategory.html.twig
Labels: Reviewed by Po

#133 Dev
  app/routing.php
  public/admin/assets/css/styles.css
  public/assets/css/style_shop.css
  public/assets/images/shop/SOLD.png
  src/Controller/WorkshopCategoryController.php
  src/Controller/WorkshopController.php
  src/Model/AbstractManager.php
  src/Model/Workshop/CategoryWorkshopManager.php
  src/Validation/CategoryWorkshopValidator.php
  src/Validation/ItemWorkshopValidator.php
  src/View/Admin/header.html.twig
  src/View/Admin/workshop.html.twig
  src/View/Admin/workshopCategory.html.twig
  src/View/Home/shop.html.twig
Labels: Reviewed by Po

#137 Fix create bike
  app/routing.php
  src/Controller/BikeController.php
  src/Model/BikeManager.php
  src/View/Admin/addBike.html.twig
Labels: Reviewed by Po

#130 S5 us33 cafe/cantine delete
  app/routing.php
  public/admin/assets/js/cateringDelete.js
  src/Controller/CateringController.php
  src/View/Admin/catering.html.twig
Labels: Reviewed by Po

#144 Fix atelier validation
  src/Validation/ItemWorkshopValidator.php
Labels: Reviewed by Po

#145 Fix_Boutique_prix
  public/assets/css/style_shop.css
  src/View/Home/shop.html.twig
Labels: Reviewed by Po

#146 Dev To Master
  app/routing.php
  public/admin/assets/js/cateringDelete.js
  public/assets/css/style_shop.css
  src/Controller/BikeController.php
  src/Controller/CateringController.php
  src/Model/BikeManager.php
  src/Validation/ItemWorkshopValidator.php
  src/View/Admin/addBike.html.twig
  src/View/Admin/catering.html.twig
  src/View/Home/shop.html.twig
Labels: Reviewed by Po

#148 Fix_Assets_optimisation_des_ressources
  public/assets/images/background_remaster3.png
  public/assets/images/background_remaster3_XS.png
  public/assets/images/bg_footer.jpg
  public/assets/images/favicon.png
  public/assets/images/logo_kitchen_kustoms.png
  public/assets/images/logo_kitchen_kustoms_nav.png
  public/assets/images/logo_kitchen_kustoms_nav_mobile.png
  public/assets/images/shop/card1.png
  public/assets/images/shop/card2.png
  public/assets/images/shop/card3.png
  public/assets/images/shop/card4.png
  public/assets/images/shop/card5.png
  public/assets/images/shop/card6.png
  public/assets/images/shop/card7.png
  public/assets/images/shop/card8.png
Labels: Reviewed by Po

#150 S5 us27 atelier admin delete item
  app/routing.php
  public/admin/assets/js/itemWorkshopDelete.js
  src/Controller/WorkshopController.php
  src/View/Admin/workshop.html.twig
Labels: Reviewed by Po

#152 Fix burger color
  public/assets/css/styles.css
Labels: Reviewed by Po

#151 S5 us26 atelier update
  app/routing.php
  src/Controller/WorkshopController.php
  src/Model/Workshop/ItemWorkshopManager.php
  src/View/Admin/updateItemWorkshop.html.twig
  src/View/Admin/workshop.html.twig
Labels: Correction done, Reviewed by Po

#156 suppression de lignes en double
  public/assets/pdf/tarifs-atelier.pdf
  src/Model/BikeManager.php
Labels: Reviewed by Po

#160 Dev To Master
  app/routing.php
  public/admin/assets/js/itemWorkshopDelete.js
  public/assets/css/styles.css
  public/assets/images/background_remaster3.png
  public/assets/images/background_remaster3_XS.png
  public/assets/images/bg_footer.jpg
  public/assets/images/favicon.png
  public/assets/images/logo_kitchen_kustoms.png
  public/assets/images/logo_kitchen_kustoms_nav.png
  public/assets/images/logo_kitchen_kustoms_nav_mobile.png
  public/assets/images/shop/card1.png
  public/assets/images/shop/card2.png
  public/assets/images/shop/card3.png
  public/assets/images/shop/card4.png
  public/assets/images/shop/card5.png
  public/assets/images/shop/card6.png
  public/assets/images/shop/card7.png
  public/assets/images/shop/card8.png
  public/assets/pdf/tarifs-atelier.pdf.dist
  src/Controller/CateringController.php
  src/Controller/PdfController.php
  src/Controller/WorkshopController.php
  src/Model/BikeManager.php
  src/Model/ItemCatering.php
  src/Model/ItemCateringManager.php
  src/Model/UplodedFile.php
  src/Model/Workshop/ItemWorkshopManager.php
  src/View/Admin/header.html.twig
  src/View/Admin/updateItemWorkshop.html.twig
  src/View/Admin/uploadPdf.html.twig
  src/View/Admin/workshop.html.twig
Labels: Reviewed by Po

#161 S5 us31 create cafe cantine
  app/routing.php
  src/Controller/CateringController.php
  src/Model/ItemCateringManager.php
  src/View/Admin/addCatering.html.twig
  src/View/Admin/catering.html.twig
Labels: Reviewed by Po

#162 S5 us42 carte cafe
  public/assets/pdf/tarifs-cafe-save.pdf
  public/assets/pdf/tarifs-cafe.pdf
  public/assets/pdf/tarifs-workshop-save.pdf
  public/assets/pdf/tarifs-workshop.pdf
  src/Controller/PdfController.php
  src/View/Admin/uploadPdf.html.twig
  src/View/Home/catering.html.twig
  src/View/Home/workshop.html.twig
Labels: Reviewed by Po

#155 S5_US40_Atelier Categories Update
  app/routing.php
  src/Controller/WorkshopCategoryController.php
  src/Model/Workshop/CategoryWorkshopManager.php
  src/Validation/CategoryWorkshopValidator.php
  src/Validation/Validation.php
  src/Validation/Validator/AbstractValidator.php
  src/Validation/Validator/MaxLength.php
  src/Validation/Validator/NotEmpty.php
  src/View/Admin/updateCategoryWorkshop.html.twig
  src/View/Admin/workshopCategory.html.twig
Labels: Correction done, Question ?, Reviewed by Po

#172 S5 us43 admin categorie delete
  app/routing.php
  public/admin/assets/js/deleteWorkshopCategorie.js
  src/Controller/WorkshopCategoryController.php
  src/Model/AbstractManager.php
  src/Model/Workshop/CategoryWorkshopManager.php
  src/View/Admin/workshopCategory.html.twig
Labels: Reviewed by Po

#176 S5 fix reduce image size vis atelier
  public/assets/images/vis_atelier.jpg
Labels: Reviewed by Po

#175 S5_US32_café/cantine_admin_UPDATE
  app/routing.php
  src/Controller/CateringController.php
  src/Model/ItemCateringManager.php
  src/View/Admin/catering.html.twig
  src/View/Admin/updateItemCatering.html.twig
Labels: Correction done, Reviewed by Po

#180 S5 fix form admin inline
  public/admin/assets/css/styles.css
  src/View/Admin/bike.html.twig
  src/View/Admin/catering.html.twig
  src/View/Admin/workshop.html.twig
  src/View/Admin/workshopCategory.html.twig
Labels: Reviewed by Po

#182 S5 Fix_changement taille icone
  public/assets/css/styles.css
  public/assets/images/bolt_BLACK_24.svg
  public/assets/images/bolt_BLACK_32.svg
  public/assets/images/wrench_and_fork_BLACK_16.svg
  public/assets/images/wrench_and_fork_BLACK_24.svg
  src/View/Home/catering.html.twig
  src/View/Home/workshop.html.twig
Labels: Reviewed by Po

#183 S5 fix css button download pdf
  public/assets/css/styles.css
  src/View/Home/catering.html.twig
  src/View/Home/workshop.html.twig
Labels: Reviewed by Po

#185 S5_US44 Ajout validation Add Catering
  src/Controller/CateringController.php
  src/Validation/CateringValidator.php
  src/Validation/Validator/IsNumeric.php
  src/View/Admin/addCatering.html.twig
Labels: Correction done, Reviewed by Po

#188 vérification du type avant déplacement d'un fichier uploadé
  src/Controller/PdfController.php
  src/Model/UplodedFile.php
  src/View/Admin/uploadPdf.html.twig
Labels: Reviewed by Po

#189 fix bug envoie vide et type erreur dynamique
  src/Controller/PdfController.php
  src/Model/UplodedFile.php
Labels: Reviewed by Po

#186 S5_US46 bike validator
  public/admin/assets/js/deleteBike.js
  src/Controller/BikeController.php
  src/Model/Bike.php
  src/Validation/BikeValidator.php
  src/Validation/Validation.php
  src/View/Admin/bike.html.twig
  src/View/Admin/updateBike.html.twig
Labels: Correction done, Reviewed by Po

#190 Dev To master
  public/admin/assets/css/styles.css
  public/admin/assets/js/deleteBike.js
  public/assets/css/styles.css
  public/assets/images/bolt_BLACK_24.svg
  public/assets/images/bolt_BLACK_32.svg
  public/assets/images/wrench_and_fork_BLACK_16.svg
  public/assets/images/wrench_and_fork_BLACK_24.svg
  src/Controller/BikeController.php
  src/Controller/CateringController.php
  src/Controller/PdfController.php
  src/Model/Bike.php
  src/Model/UplodedFile.php
  src/Validation/BikeValidator.php
  src/Validation/CateringValidator.php
  src/Validation/Validation.php
  src/Validation/Validator/IsNumeric.php
  src/View/Admin/addCatering.html.twig
  src/View/Admin/bike.html.twig
  src/View/Admin/catering.html.twig
  src/View/Admin/updateBike.html.twig
  src/View/Admin/uploadPdf.html.twig
  src/View/Admin/workshop.html.twig
  src/View/Admin/workshopCategory.html.twig
  src/View/Home/catering.html.twig
  src/View/Home/workshop.html.twig
Labels: Reviewed by Po
